services:
  sr2silo:
    build: .
    volumes:
      - ${SAMPLE_DIR}:/app/sample
      - ${TIMELINE_FILE}:/app/timeline.tsv
      - ${PRIMER_FILE}:/app/primers.yaml
      - ${RESULTS_DIR}:/app/results
      - ./scripts/database_config.yaml:/app/scripts/database_config.yaml
      - ./scripts/reference_genomes.json:/app/scripts/- ./scripts/database_config.yaml:/app/scripts/reference_genomes.json
    environment:
      - PYTHONUNBUFFERED=1
      - SAMPLE_DIR=${SAMPLE_DIR}
      - SAMPLE_ID=${SAMPLE_ID}
      - BATCH_ID=${BATCH_ID}
      - TIMELINE_FILE=${TIMELINE_FILE}
      - PRIMER_FILE=${PRIMER_FILE}
      - RESULTS_DIR=${RESULTS_DIR}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}

volumes:
  results:
