version: '3.8'

services:
  sr2silo:
    build: .
    env_file:
      - .github/docker-build-test.env
    volumes:
      - ${TIMELINE_FILE}:/app/timeline.tsv
      - ${PRIMER_FILE}:/app/primers.yaml
      - ${OUTPUT_FP}:/app/output.ndjson.zst
      - ./scripts/database_config.yaml:/app/scripts/database_config.yaml
      - ./scripts/reference_genomes.json:/app/scripts/reference_genomes.json
    environment:
      - PYTHONUNBUFFERED=1
      - SAMPLE_ID=${SAMPLE_ID}
      - BATCH_ID=${BATCH_ID}
      - TIMELINE_FILE=${TIMELINE_FILE}
      - PRIMER_FILE=${PRIMER_FILE}
      - OUTPUT_FP=${OUTPUT_FP}
      - DATABASE_CONFIG=${DATABASE_CONFIG}
      - REFERENCE=${REFERENCE}
      - KEYCLOAK_TOKEN_URL=${KEYCLOAK_TOKEN_URL}
      - SUBMISSION_URL=${SUBMISSION_URL}
      - CI=${CI}
      - INPUT_FILE=${INPUT_FILE}
    secrets:
      - aws_access_key_id
      - aws_secret_access_key
      - aws_default_region

secrets:
  aws_access_key_id:
    file: ./secrets/aws_access_key_id.txt
  aws_secret_access_key:
    file: ./secrets/aws_secret_access_key.txt
  aws_default_region:
    file: ./secrets/aws_default_region.txt

volumes:
  results:
  timeline_file:
