name: sr2silo
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.11
  - snakemake=8.18 # fixed as snakemake unit tests fail with 8.19
  - nextclade>=3.5.0
  - poetry>=1.8.3
