name: sr2silo-workflow
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.11
  - snakemake=8.18  # fixed as snakemake unit tests fail with 8.19
  - diamond>=2.1.0
  - smallgenomeutilities>=0.5.2
