schema:
  metadata:
    - name: sampleId
      type: string
      generateIndex: true
    - name: batchId
      type: string
      generateIndex: true
    - name: locationCode
      type: string
      generateIndex: true
    - name: samplingDate
      type: date
      generateIndex: true
    - name: locationName
      type: string
      generateIndex: true
    - name: readId
      type: string
      generateIndex: true
    - name: sr2siloVersion
      type: string
      generateIndex: true
  opennessLevel: OPEN
  instanceName: wise-sarsCoV2
  features: []
  primaryKey: readId
