file_inputs:
  metadata: "testData/small_metadata_set.tsv"
  database_config: "testData/database_config.yaml"
  reference_genomes: "testData/reference_genomes.json"
  sequence_file_directory: "testData"
file_prefixes:
  amino_acid_sequence: "gene_"
  nucleotide_sequence: "nuc_"
  unaligned_nucleotide_sequence: "unaligned_"
output_dir: "testData/output"
batch_size: 10
