file_inputs:
  metadata: "silo_input_transformer/testData/small_metadata_set.tsv"
  database_config: "silo_input_transformer/testData/database_config.yaml"
  reference_genomes: "silo_input_transformer/testData/reference_genomes.json"
  sequence_file_directory: "silo_input_transformer/testData"
file_prefixes:
  amino_acid_sequence: "gene_"
  nucleotide_sequence: "nuc_"
  unaligned_nucleotide_sequence: "unaligned_"
output_dir: "silo_input_transformer/testData/output"
batch_size: 10
