name: Poetry in Conda

on:
  push:
    branches: [ main ]  # Or your main branch name
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run black formatting check
        uses: psf/black@stable

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge, bioconda
          environment-file: environment.yml
          activate-environment: myenv

      - name: Install Poetry
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate myenv
          conda install -c conda-forge poetry

      - name: Install the module
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate myenv
          poetry install --with dev --no-interaction

      - name: Run unit tests
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate myenv
          poetry run pytest

      - name: Run unit tests
        run: poetry run pytest

      - name: Run Ruff
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate myenv
          poetry run ruff check .

      - name: Run interrogate
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate myenv
          poetry run interrogate src

      - name: Run Pyright (type checking)
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate myenv
          poetry run pyright
