name: Python Publish Workflow
on:
  workflow_call:

jobs:
  publish:
    # manually disabled here for now
    if: false
    uses: microsoft/action-python/.github/workflows/publish.yml@0.7.3
    secrets:
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      TEST_PYPI_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD  }}
